spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  server:
    ssl:
      enabled: false
server:
  address: 0.0.0.0
  port: ${PORT:8080}

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
#