spring:
  application:
    name: app
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  server:
    ssl:
      enabled: false


rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
#